version: '3'

services:
  client:
    build: ./client
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - server
  node_server:
    build: ./server
    env_file:
      - .env
    ports:
      - "8000:8000"
  flask_server:
    build: ./coffeestockAI
    env_file:
      - .env
    ports:
      - "5000:5000"