version: '3'

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
  server:
    build: ./server
    env_file:
      - .env
    ports:
      - "8000:8000"