version: '3'

services:
  node_server:
    build: ./server
    env_file:
      - .env
    ports:
      - "8000:8000"
  flask_server:
    build: ./coffeestockAI
    env_file:
      - .env
    ports:
      - "5000:5000"